export const postData = [
  {
    id: '1',
    title: 'First Post',
    content: 'This is the first post content.',
    author: 'John Doe',
    date: '2024-01-01',
    category: `Mobile`,
    links: ['http://example.com/news1'],
    thumbnail: '/greece.jpg',
  },
  {
    id: '2',
    title: 'Second Post',
    content: 'This is the second post content.',
    author: 'Jane Smith',
    date: '2024-02-01',
    category: `Tech`,
    links: ['http://example.com/news2'],
    thumbnail: '/greece.jpg',
  },
  {
    id: '3',
    title: 'Third Post',
    content: 'This is the third post content.',
    author: 'Bob Johnson',
    date: '2024-03-01',
    category: `Mobile`,
    links: ['http://example.com/news3'],
    thumbnail: '/greece.jpg',
  },
  {
    id: '4',
    title: 'Fourth Post',
    content: 'This is the fourth post content.',
    author: 'Alice Wilson',
    date: '2024-04-01',
    category: `Tech`,
    links: ['http://example.com/news4', 'http://example.com/news10'],
    thumbnail: '/greece.jpg',
  },
  {
    id: '5',
    title: 'Fifth Post',
    content: 'This is the fifth post content.',
    author: 'Charlie Brown',
    date: '2024-05-01',
    category: `Mobile`,
    links: ['http://example.com/news5'],
    thumbnail: '/greece.jpg',
  },
  {
    id: '6',
    title: 'Sixth Post',
    content: 'This is the sixth post content.',
    author: 'David Garcia',
    date: '2024-06-01',
    category: `Tech`,
    links: ['http://example.com/news6'],
  },
  {
    id: '7',
    title: 'Seventh Post',
    content: 'This is the seventh post content.',
    author: 'Emily Davis',
    date: '2024-07-01',
    category: `Mobile`,
    links: ['http://example.com/news7'],
    thumbnail: '/greece.jpg',
  },
];

export const categoryData = [
  {
    id: '1',
    name: 'Technology',
  },
  {
    id: '2',
    name: 'Tips & Tricks',
  },
  {
    id: '3',
    name: 'AI',
  },
  {
    id: '4',
    name: 'Programming',
  },
];
