import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { NextProvider } from '@/components/NextProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextProvider>
          <div className='lg:max-w-[900px] border mx-auto lg:px-16 py-8 shadow-xl min-h-screen flex flex-col px-8'>
            <Navbar />
            <div className='grow'> {children}</div>
            <Footer />
          </div>
        </NextProvider>
      </body>
    </html>
  );
}
